// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="parker,hls_ip_2017_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.598000,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1211,HLS_SYN_LUT=710}" *)

module parker (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in1,
        in2,
        in3,
        in4,
        in5,
        in6,
        ap_return,
        trigger_in
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] in1;
input  [31:0] in2;
input  [31:0] in3;
input  [31:0] in4;
input  [31:0] in5;
input  [31:0] in6;
input [0:0] trigger_in;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] tmp_4_fu_72_p2;
reg   [0:0] tmp_4_reg_227;
wire   [31:0] t4_fu_104_p2;
reg   [31:0] t4_reg_232;
wire   [0:0] tmp_9_fu_110_p2;
reg   [0:0] tmp_9_reg_237;
wire   [31:0] t4_2_fu_116_p2;
reg   [31:0] t4_2_reg_242;
wire   [31:0] t4_3_fu_122_p2;
reg   [31:0] t4_3_reg_247;
wire    ap_CS_fsm_state2;
wire   [31:0] t2_fu_66_p2;
wire   [0:0] tmp_5_fu_78_p2;
wire   [31:0] t6_5_fu_90_p2;
wire   [31:0] t6_4_fu_84_p2;
wire   [31:0] t6_6_fu_96_p3;
wire   [0:0] tmp_1_fu_133_p2;
wire   [31:0] t6_3_fu_144_p2;
wire   [31:0] t6_fu_139_p2;
wire   [31:0] t4_4_fu_157_p3;
wire   [31:0] t4_1_fu_162_p3;
wire   [0:0] tmp_fu_128_p2;
wire   [31:0] t6_1_fu_149_p3;
wire   [31:0] t6_7_fu_168_p2;
wire   [31:0] t6_2_fu_173_p3;
wire   [0:0] tmp_s_fu_181_p2;
wire   [31:0] out1_1_fu_192_p2;
wire   [31:0] out1_fu_187_p2;
reg   [1:0] ap_NS_fsm;
reg [31:0] reg1;
wire [31:0] reg_out1;
wire [31:0] mux_out1;
wire [31:0] mux_out_neg1;
reg [31:0] reg2;
wire [31:0] reg_out2;
wire [31:0] mux_out2;
wire [31:0] mux_out_neg2;
wire [0:0] temp1;
wire [0:0] temp2;
wire [0:0] temp12;


// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        reg1 <= 1'b0;
        reg2 <= 1'b0;
        t4_2_reg_242 <= t4_2_fu_116_p2;
        t4_3_reg_247 <= t4_3_fu_122_p2;
        t4_reg_232 <= t4_fu_104_p2;
        tmp_4_reg_227 <= tmp_4_fu_72_p2;
        tmp_9_reg_237 <= tmp_9_fu_110_p2;
    end else if ((1'b1 == ap_CS_fsm_state2) & (trigger_in == 1'b1)) begin
    	reg1 <= mux_out_neg1;
    	reg2 <= mux_out_neg2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign reg_out1 = reg1;

assign reg_out2 = reg2;

assign temp1 = (trigger_in == 1'b1)? 1'b1 : 1'b0;
assign temp2 = (1'b1 == ap_CS_fsm_state2)? 1'b1 : 1'b0;
assign temp12 = temp1 & temp2;

assign mux_out1 = (temp12 == 1'b1) ? reg_out1 : in2;

assign mux_out2 = (temp12 == 1'b1) ? reg_out2 : in3;

assign mux_out_neg1 = ~mux_out1;

assign mux_out_neg2 = ~mux_out2;

assign t4_2_fu_116_p2 = ( mux_out1 + 32'd4);

assign t4_3_fu_122_p2 = (mux_out2 - in5);

assign ap_return = ((tmp_s_fu_181_p2[0:0] === 1'b1) ? out1_1_fu_192_p2 : out1_fu_187_p2);

assign out1_1_fu_192_p2 = (in5 + 32'd8);

assign out1_fu_187_p2 = ($signed(in1) + $signed(32'd4294967291));

assign t2_fu_66_p2 = (32'd0 - in3);

assign t4_1_fu_162_p3 = ((tmp_4_reg_227[0:0] === 1'b1) ? t4_reg_232 : t4_4_fu_157_p3);

//assign t4_2_fu_116_p2 = ( mux_out1 + 32'd4);

//assign t4_3_fu_122_p2 = (mux_out2 - in5);

assign t4_4_fu_157_p3 = ((tmp_9_reg_237[0:0] === 1'b1) ? t4_3_reg_247 : t4_2_reg_242);

assign t4_fu_104_p2 = (t6_6_fu_96_p3 - in4);

assign t6_1_fu_149_p3 = ((tmp_1_fu_133_p2[0:0] === 1'b1) ? t6_3_fu_144_p2 : t6_fu_139_p2);

assign t6_2_fu_173_p3 = ((tmp_fu_128_p2[0:0] === 1'b1) ? t6_1_fu_149_p3 : t6_7_fu_168_p2);

assign t6_3_fu_144_p2 = (32'd8 - in4);

assign t6_4_fu_84_p2 = (in2 + in1);

assign t6_5_fu_90_p2 = (32'd0 - in2);

assign t6_6_fu_96_p3 = ((tmp_5_fu_78_p2[0:0] === 1'b1) ? t6_5_fu_90_p2 : t6_4_fu_84_p2);

assign t6_7_fu_168_p2 = (t4_1_fu_162_p3 + in4);

assign t6_fu_139_p2 = (in2 + 32'd5);

assign tmp_1_fu_133_p2 = ((in6 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_72_p2 = ((in2 == t2_fu_66_p2) ? 1'b1 : 1'b0);

assign tmp_5_fu_78_p2 = ((in4 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_9_fu_110_p2 = ((in1 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_fu_128_p2 = ((in5 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_181_p2 = ((t6_2_fu_173_p3 == 32'd0) ? 1'b1 : 1'b0);

endmodule //parker
